version: '3.8'

services:
  app:
    build:
      context: ./docker/php
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage:rw
      - ./bootstrap/cache:/var/www/html/bootstrap/cache:rw
    ports:
      - 9000:9000
      - 5173:5173
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:wJj2DBm4orbtk5HB3m6AShOOzueJIz3oKNWC4eWnYqw=
    networks:
      - laravel

  webserver:
    image: nginx:latest
    container_name: laravel_webserver
    depends_on:
      - app
    ports:
      - 8087:80
      - 44387:443
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/certs:/etc/nginx/certs
    networks:
      - laravel


  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel:
